In [1]:
import os
import librosa
import numpy as np 
import pandas as pd 
from octave_band import plot_custom_bands
import matplotlib.pyplot as plt
import matplotlib.colors as colors
from scipy.signal import spectrogram
%matplotlib qt

In [2]:
wavfile = 'train_recordings/hour0101.wav'
data, samplerate = librosa.load(wavfile, sr=1000)

In [3]:
def max_pooling(array, pool_size, pool_overlap=(0,0)):
    if pool_overlap:
        if (pool_overlap[0] >= pool_size[0]) and (pool_overlap[1] >= pool_size[1]):
            print('pool_overlap must be less than pool_size')
            return

    output = []
    for i in range(0, array.shape[0]-pool_size[0]+pool_overlap[0], pool_size[0]-pool_overlap[0]):
        row = []
        for j in range(0, array.shape[1]-pool_size[1]+pool_overlap[1], pool_size[1]-pool_overlap[1]):
            maximum = max(np.array(array[i:i+pool_size[0], j:j+pool_size[1]]).flatten())
            row.append(maximum)
        output.append((row))
    return output

In [4]:
def quick_plot_max_pooling(data, array, samplerate, nperseg=100, noverlap=0, nfft=40, pool_size=(1,1), pool_overlap=(0,0), vmin=None, vmax=None, ylim=None):
    if array==None:
        fig = plt.figure(figsize=(32,18), dpi=200)
        f0, t0, Sxx0 = spectrogram(data, fs=samplerate, window='hamming', nperseg=nperseg, noverlap=noverlap, nfft=nfft)
        pooled = max_pooling(Sxx0, pool_size=pool_size, pool_overlap=pool_overlap)
        if ylim:
            lim = [(ylim[0]*len(pooled))//500, (ylim[1]*len(pooled))//500]
            pooled = pooled[lim[0]:lim[1]]
        else:
            ylim = [0,500]
        f = np.linspace(ylim[0],ylim[1],len(pooled))
        t = np.linspace(0,3600,len(pooled[0]))
        plt.pcolormesh(t, f, pooled, norm=colors.LogNorm(vmin=vmin, vmax=vmax))
        #if ylim:    ax[i].set_ylim(ylim[0], ylim[1])
        print('max value: '+str(max(max(pooled))))
        print('average value: '+str(np.mean(pooled)))
        plt.savefig('something.pdf', bbox_inches='tight')
    else:
        fig, ax = plt.subplots(ncols=len(array), figsize=(3*len(array),5))
        for i in range(len(array)):
            f0, t0, Sxx0 = spectrogram(data[samplerate*array[i][0]:samplerate*array[i][1]], fs=samplerate, window='hamming', nperseg=nperseg, noverlap=noverlap, nfft=nfft)
            pooled = max_pooling(Sxx0, pool_size=pool_size, pool_overlap=pool_overlap)
            if ylim:
                lim = [(ylim[0]*len(pooled))//500, (ylim[1]*len(pooled))//500]
                pooled = pooled[lim[0]:lim[1]]
            else:
                ylim = [0,500]
            f = np.linspace(ylim[0],ylim[1],len(pooled))
            t = np.linspace(0,(array[i][1]-array[i][0]),len(pooled[0]))
            im = ax[i].pcolormesh(t, f, pooled, norm=colors.LogNorm(vmin=vmin, vmax=vmax))
            #if ylim:    ax[i].set_ylim(ylim[0], ylim[1])
            print('max value: '+str(max(max(pooled))))
            print('average value: '+str(np.mean(pooled)))
            fig.colorbar(im, ax=ax[i])
    plt.show()

# cen_eas

In [5]:
cen_eas = np.array(pd.read_csv('judged_timings/cen_eas_01.csv').timings)
print(cen_eas)

[ 202  507  817 1474]


In [6]:
array = [[193,204],[497,512],[807,822],[1464,1478]]
quick_plot_max_pooling(data, array, samplerate, nperseg=100, noverlap=50, nfft=10000, pool_size=(5,5), pool_overlap=(1,1), vmin=2e-7, vmax=6e-7, ylim=(80,300))

max value: 2.2276228e-07
average value: 4.147011e-08
max value: 5.3211767e-07
average value: 5.2062255e-08
max value: 2.1911963e-07
average value: 3.636674e-08
max value: 4.6927062e-07
average value: 3.6037633e-08


# cen_wes

In [7]:
cen_wes = np.array(pd.read_csv('judged_timings/cen_wes_01.csv').timings)
print(cen_wes)

[ 310  665  912 1314 1496]


In [8]:
array = [[300,320],[655,675],[902,922],[1304,1324],[1486,1506]]
quick_plot_max_pooling(data, array, samplerate, nperseg=100, noverlap=0, nfft=10000, pool_size=(10,10), pool_overlap=(5,5), vmin=1.5e-7, vmax=5e-7, ylim=(50,150))

max value: 2.2292251e-07
average value: 8.2482295e-08
max value: 5.093607e-07
average value: 7.634975e-08
max value: 1.6464158e-07
average value: 1.0219975e-07
max value: 3.228516e-07
average value: 7.050449e-08
max value: 4.753344e-07
average value: 8.064557e-08


# bak_sou

In [9]:
bak_sou = np.array(pd.read_csv('judged_timings/bak_sou_01.csv').timings)
print(bak_sou)

[ 297  498  766 1064 1158 1538]


In [10]:
array = [[287,307],[488,508],[756,776],[1054,1074],[1148,1168],[1528,1548]]
quick_plot_max_pooling(data, array, samplerate, nperseg=100, noverlap=0, nfft=10000, pool_size=(5,5), pool_overlap=(1,1), vmin=6e-8, vmax=2e-7, ylim=(50,300))

max value: 1.220259e-07
average value: 3.1514258e-08
max value: 5.587115e-07
average value: 3.622216e-08
max value: 1.8678303e-07
average value: 2.4703706e-08
max value: 1.4642113e-07
average value: 1.9509093e-08
max value: 6.818239e-08
average value: 1.2090996e-08
max value: 8.174079e-08
average value: 1.9559252e-08


# bak_nor

In [12]:
bak_nor = np.array(pd.read_csv('judged_timings/bak_nor_01.csv').timings)
print(bak_nor)

[ 359  963 1553]


In [42]:
array = [[349,369],[953,973],[1543,1563]]
quick_plot_max_pooling(data, array, samplerate, nperseg=100, noverlap=0, nfft=10000, pool_size=(5,5), pool_overlap=(1,1), vmin=1e-8, vmax=5e-7, ylim=(60,180))

max value: 1.3704891e-08
average value: 1.8111171e-08
max value: 1.8212221e-08
average value: 1.6537397e-08
max value: 6.110274e-08
average value: 2.1702748e-08


# vic_sou

In [14]:
vic_sou = np.array(pd.read_csv('judged_timings/vic_sou_01.csv').timings)
print(vic_sou)

[ 146  719 1360]


In [41]:
array = [[146,166],[713,729],[1358,1372]]
quick_plot_max_pooling(data, array, samplerate, nperseg=100, noverlap=0, nfft=10000, pool_size=(5,5), pool_overlap=(1,1), vmin=1e-8, vmax=5e-7, ylim=(60,180))

max value: 3.045865e-07
average value: 5.1627218e-08
max value: 3.392943e-08
average value: 1.8632386e-08
max value: 7.984824e-08
average value: 2.1552868e-08


# vic_nor

In [16]:
vic_nor = np.array(pd.read_csv('judged_timings/vic_nor_01.csv').timings)
print(vic_nor)

[ 104  279  564  814 1016 1332 1629]


In [17]:
array = [[94,114],[269,289],[554,574],[804,824],[1006,1026],[1322,1342],[1619,1639]]
quick_plot_max_pooling(data, array, samplerate, nperseg=100, noverlap=0, nfft=10000, pool_size=(5,5), pool_overlap=(1,1), vmin=1e-9, vmax=6e-7, ylim=(30,300))

max value: 1.8593593e-07
average value: 1.0446886e-08
max value: 1.3279904e-07
average value: 1.7134642e-08
max value: 5.8707307e-08
average value: 8.539256e-09
max value: 9.315002e-08
average value: 3.0695112e-08
max value: 2.6262919e-08
average value: 7.2508146e-09
max value: 2.6035513e-08
average value: 6.2880625e-09
max value: 4.2732609e-07
average value: 7.0271517e-09


# trying to do the isolation

# cen_eas

### set min at 2e-7 around 95-120Hz, should be nothing above 60-80 (retrospectively 115-130 with min of 0.0004/5 seems to only show both cen)

In [18]:
wavfile = 'train_recordings/hour0001.wav'

In [20]:
a = [[60,80],[95,120]]
plot_custom_bands(wavfile, array=a, samplerate=1000,  lines=['cen_eas'], ma=1000, vmin=[0.0008,0.001])

# cen_wes

### use same plot as above, just requires 60-80

In [21]:
plot_custom_bands(wavfile, array=a, samplerate=1000,  lines=['cen_wes'], judged_lines=['cen_eas','cen_wes'], ma=1000, vmin=[0.0008,0.0008])

# bak_sou

### requires 80-110, 180-280 and none 50-70, 115-130, 160-170ish
### largest peak expected around 180-280

In [22]:
a = [[80,110],[180,280]]
plot_custom_bands(wavfile, array=a, samplerate=1000,  lines=['bak_sou'], judged_lines=['cen_eas', 'cen_wes'], ma=1000, vmin=[0.0005,0.001])

# bak_nor

### peaks 100-115, 130-150

In [35]:
wavfile = 'train_recordings/hour0001.wav'
a = [[101,111],[133,143],[200,250]]
plot_custom_bands(wavfile, array=a, samplerate=1000,  lines=['bak_nor'], judged_lines=['cen_eas','cen_wes','bak_sou'], ma=1000, vmin=[0.0,0.0,0])

# vic_sou

### peaks expected same as above (maybe slightly lower first band)

In [48]:
wavfile = 'train_recordings/hour0001.wav'
a = [[101,111],[133,143],[200,250]]
plot_custom_bands(wavfile, array=a, samplerate=1000,  lines=['vic_sou'], judged_lines=['cen_eas','cen_wes','bak_sou','bak_nor'], ma=1000, vmin=[0.0,0.0,0])

In [46]:
wavfile = 'train_recordings/hour0102.wav'
a = [[101,111],[133,143],[200,250]]
plot_custom_bands(wavfile, array=a, samplerate=1000,  lines=['vic_sou','bak_nor'], ma=1000, vmin=[0.0,0.0,0])